// Synthetic local workflow; no external data or disclosure requests are sent.
const { createRequire } = require('node:module');
const path = require('node:path');
const fs = require('node:fs');
const requireFrontend = createRequire(path.resolve(__dirname, '../frontend/package.json'));
const { chromium } = requireFrontend('playwright');
const root = path.resolve(__dirname, '..');
(async () => {
  const credentials = fs.readFileSync(path.join(root, '.local/bootstrap-credentials.txt'), 'utf8');
  const out = path.join(root, 'tmp/browser');
  fs.mkdirSync(out, { recursive: true });
  const browser = await chromium.launch({ channel: process.env.ATLAS_BROWSER_CHANNEL || (process.platform === 'win32' ? 'msedge' : undefined), headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://127.0.0.1:8787');
  await page.getByLabel('Username', { exact: true }).fill('investigator');
  await page.getByLabel('Password', { exact: true }).fill(credentials.match(/^investigator: (.+)$/m)[1].trim());
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('button', { name: 'Open training case', exact: true }).click();
  await page.getByRole('heading', { name: 'Example Exchange Alpha', exact: true }).waitFor({ timeout: 20000 });
  const parentReport = await page.getByRole('link', { name: 'Report', exact: true }).getAttribute('href');
  const parentId = parentReport.split('/')[3];
  const parent = await (await page.request.get('http://127.0.0.1:8787/api/analyses/' + parentId)).json();
  await page.getByRole('button', { name: 'Plan within a request budget' }).click();
  await page.getByLabel('HTTP request budget', { exact: true }).fill('4');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await page.getByRole('button', { name: 'Execute training expansion', exact: true }).click();
  await page.getByRole('heading', { name: 'Execute the selected evidence queries', exact: true }).waitFor();
  await page.getByText(/TRAINING ONLY: adds an invented example transfer/).waitFor();
  await page.screenshot({ path: path.join(out, 'query-review.png'), fullPage: true });
  await page.getByRole('button', { name: 'Start selected queries', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.getByText('Query execution complete', { exact: true }).waitFor({ timeout: 25000 });
  const report = await page.getByRole('link', { name: 'Report', exact: true }).getAttribute('href');
  const jobId = report.split('/')[3];
  if (jobId === parentId) throw Error('Execution replaced the parent job');
  const result = await (await page.request.get('http://127.0.0.1:8787/api/analyses/' + jobId)).json();
  if (!result.result.analysis.candidates.some(c => c.path.includes('fixture-expanded-deposit'))) throw Error('Training expansion missing');
  if (result.result.execution.reserved_request_slots !== 0) throw Error('Synthetic execution spent provider budget');
  const preserved = await (await page.request.get('http://127.0.0.1:8787/api/analyses/' + parentId)).json();
  if (JSON.stringify(preserved.result) !== JSON.stringify(parent.result)) throw Error('Parent evidence changed');
  await page.screenshot({ path: path.join(out, 'query-result.png'), fullPage: true });
  const pdf = await page.request.get('http://127.0.0.1:8787' + report);
  if (!pdf.ok()) throw Error('Query report export failed');
  fs.writeFileSync(path.join(out, 'query-report.pdf'), await pdf.body());
  await page.setViewportSize({ width: 390, height: 844 });
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1);
  await page.screenshot({ path: path.join(out, 'query-mobile.png'), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1050 });
  await page.getByRole('button', { name: 'Evidence', exact: true }).click();
  const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('link', { name: 'Signed evidence bundle' }).click()]);
  const bundle = path.join(out, 'query-evidence.zip');
  await download.saveAs(bundle);
  await page.getByRole('button', { name: 'Verify evidence', exact: true }).click();
  await page.getByLabel('Evidence ZIP (maximum 10 MB)').setInputFiles(bundle);
  await page.getByRole('button', { name: 'Verify bundle', exact: true }).click();
  await page.getByText('Integrity valid · replay matched', { exact: true }).waitFor();
  const checks = ['immutable plan review', 'selected query execution', 'explicit synthetic zero-HTTP expansion', 'superseding analysis', 'parent evidence preserved', 'PDF export', 'signed bundle replay', 'mobile overflow'];
  const resultLog = { passed: !errors.length && !overflow, checks, pageErrors: errors, mobileOverflow: overflow };
  fs.writeFileSync(path.join(out, 'query-results.json'), JSON.stringify(resultLog, null, 2));
  console.log(JSON.stringify(resultLog));
  await browser.close();
  if (!resultLog.passed) process.exitCode = 1;
})().catch(e => { console.error(e); process.exit(1); });
