// Explicit synthetic CCTP review exercise. No network evidence or real service identity is asserted.
const { createRequire } = require("node:module");
const path = require("node:path");
const fs = require("node:fs");
const requireFrontend = createRequire(path.resolve(__dirname, "../frontend/package.json"));
const { chromium } = requireFrontend("playwright");
const root = path.resolve(__dirname, "..");
(async () => {
  const credentials = fs.readFileSync(path.join(root, ".local/bootstrap-credentials.txt"), "utf8");
  const output = path.join(root, "tmp/browser");
  fs.mkdirSync(output, { recursive: true });
  const browser = await chromium.launch({ channel: process.env.ATLAS_BROWSER_CHANNEL || (process.platform === "win32" ? "msedge" : undefined), headless: true });
  const errors = [];
  async function login(name) {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1050 } });
    const page = await context.newPage();
    page.on("pageerror", e => errors.push(e.message));
    await page.goto("http://127.0.0.1:8787");
    await page.getByLabel("Username", { exact: true }).fill(name);
    await page.getByLabel("Password", { exact: true }).fill(credentials.match(new RegExp("^" + name + ": (.+)$", "m"))[1].trim());
    await page.getByRole("button", { name: "Sign in", exact: true }).click();
    await page.getByRole("heading", { name: "Investigations", exact: true }).waitFor();
    return page;
  }
  const i = await login("investigator"), r = await login("reviewer");
  await i.getByRole("button", { name: "Review a bridge case", exact: true }).click();
  await i.getByRole("heading", { name: "Cross-chain bridge · training investigation", exact: true }).waitFor();
  await i.getByRole("button", { name: "Reassess recorded evidence", exact: true }).waitFor({ timeout: 20000 });
  if (await i.getByRole("heading", { name: "Example Cross-chain Exchange", exact: true }).count()) throw Error("Unreviewed proof produced custody");
  await i.getByRole("button", { name: "Evidence", exact: true }).click();
  await i.getByRole("button", { name: "Propose training bridge", exact: true }).click();
  await i.getByLabel("Bridge evidence purpose", { exact: true }).selectOption("training");
  await i.getByLabel("Proof provenance and verification performed", { exact: true }).fill("Synthetic UI test only: invented receipts and a local test signer, not Circle evidence.");
  await i.getByRole("button", { name: "Save", exact: true }).click();
  await i.getByRole("dialog").waitFor({ state: "hidden" });
  async function reopen(page, tab = "Evidence") {
    await page.reload();
    await page.getByRole("heading", { name: "Investigations", exact: true }).waitFor();
    await page.locator(".case-row").first().click();
    await page.getByRole("heading", { name: "Cross-chain bridge · training investigation", exact: true }).waitFor();
    await page.getByRole("button", { name: tab, exact: true }).click();
  }
  await reopen(r);
  const proofRow = r.locator(".record-row").filter({ hasText: "CCTP V2 bridge proof" });
  await proofRow.getByRole("button", { name: "Review", exact: true }).click();
  await r.getByLabel("Review rationale and verification performed").fill("Independent synthetic review of protocol layout and deliberately local key provenance; training only.");
  await r.getByRole("button", { name: "Record decision", exact: true }).click();
  await r.getByRole("dialog").waitFor({ state: "hidden" });
  await proofRow.getByText("approved", { exact: true }).waitFor();
  await reopen(i);
  await i.getByRole("button", { name: "Reassess recorded evidence", exact: true }).click();
  await i.getByRole("heading", { name: "Example Cross-chain Exchange", exact: true }).waitFor({ timeout: 20000 });
  await i.getByRole("button", { name: "Evidence", exact: true }).click();
  await i.getByRole("button", { name: "Inspect CCTP delivery", exact: true }).click();
  await i.getByText("CCTP V2 delivery · Ethereum → Polygon", { exact: true }).waitFor();
  await i.getByText("Burned 1 USDC; fee 0.01; minted 0.99.", { exact: true }).waitFor();
  await i.screenshot({ path: path.join(output, "bridge-investigation.png"), fullPage: true });
  const pdfResponse = await i.context().request.get("http://127.0.0.1:8787" + await i.getByRole("link", { name: "Report", exact: true }).getAttribute("href"));
  if (!pdfResponse.ok()) throw Error("Bridge PDF report failed");
  fs.writeFileSync(path.join(output, "bridge-report.pdf"), await pdfResponse.body());
  await i.getByRole("button", { name: "Assumptions", exact: true }).click();
  await i.locator(".assertion-line").filter({ hasText: "synthetic-cctp-v2" }).getByRole("button", { name: "Challenge" }).click();
  await i.getByRole("heading", { name: "1 custody path(s) removed", exact: true }).waitFor();
  await i.getByRole("button", { name: "Evidence", exact: true }).click();
  const [download] = await Promise.all([i.waitForEvent("download"), i.getByRole("link", { name: "Signed evidence bundle" }).click()]);
  const bundlePath = path.join(output, "bridge-evidence.zip");
  await download.saveAs(bundlePath);
  await i.getByRole("button", { name: "Verify evidence", exact: true }).click();
  await i.getByLabel("Evidence ZIP (maximum 10 MB)").setInputFiles(bundlePath);
  await i.getByRole("button", { name: "Verify bundle", exact: true }).click();
  await i.getByText("Integrity valid · replay matched", { exact: true }).waitFor();
  await reopen(i);
  await i.locator(".record-row").filter({ hasText: "CCTP V2 bridge proof" }).getByRole("button", { name: "Propose withdrawal" }).click();
  await i.getByLabel("Reason and supporting evidence").fill("Synthetic test correction: withdraw the bridge proof and invalidate dependent paths.");
  await i.getByRole("button", { name: "Save", exact: true }).click();
  await i.getByRole("dialog").waitFor({ state: "hidden" });
  await reopen(r);
  await r.locator(".record-row").filter({ hasText: "Evidence withdrawal" }).getByRole("button", { name: "Review", exact: true }).click();
  await r.getByLabel("Review rationale and verification performed").fill("Independent training review approves withdrawal of the synthetic bridge proof.");
  await r.getByRole("button", { name: "Record decision", exact: true }).click();
  await r.getByRole("dialog").waitFor({ state: "hidden" });
  await reopen(i);
  await i.getByText(/Supporting evidence was withdrawn after this analysis/).waitFor();
  if (await i.getByRole("link", { name: "Report", exact: true }).count()) throw Error("Stale bridge report remains offered");
  await i.getByRole("button", { name: "Reassess recorded evidence", exact: true }).click();
  await i.getByRole("button", { name: "Reassess recorded evidence", exact: true }).waitFor({ timeout: 20000 });
  await i.getByRole("button", { name: "Evidence", exact: true }).click();
  if (await i.getByRole("button", { name: "Inspect CCTP delivery", exact: true }).count()) throw Error("Withdrawn bridge survived reassessment");
  await i.setViewportSize({ width: 390, height: 844 });
  const overflow = await i.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1);
  const result = { checks: ["synthetic unreviewed abstention", "proof proposal", "independent review", "reassessment", "cross-chain graph", "burn/fee/mint inspection", "PDF export", "bridge provenance challenge", "signed bundle replay", "reviewed withdrawal", "stale report guard", "superseding analysis", "mobile overflow"], pageErrors: errors, mobileOverflow: overflow };
  fs.writeFileSync(path.join(output, "bridge-results.json"), JSON.stringify(result, null, 2));
  console.log(JSON.stringify({ passed: !errors.length && !overflow, ...result }));
  await browser.close();
  if (errors.length || overflow) process.exitCode = 1;
})().catch(e => { console.error(e); process.exit(1); });
